// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWBZ7eLjd8I8NNwfPHoAr7PdeI3lTZ5qw',
    appId: '1:1094149306983:web:a08604a408407523c872c2',
    messagingSenderId: '1094149306983',
    projectId: 'pfee-76597',
    authDomain: 'pfee-76597.firebaseapp.com',
    storageBucket: 'pfee-76597.appspot.com',
    measurementId: 'G-5Y3WJK2DDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jx6THXBaIdRs4WLLW0JHZyt8cUkH_dM',
    appId: '1:1094149306983:android:14ff73ab6c75743fc872c2',
    messagingSenderId: '1094149306983',
    projectId: 'pfee-76597',
    storageBucket: 'pfee-76597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPzmblxhYgG6VtRjxUK7SXbTK0yGFcPs',
    appId: '1:1094149306983:ios:4e812677b3a2b93ec872c2',
    messagingSenderId: '1094149306983',
    projectId: 'pfee-76597',
    storageBucket: 'pfee-76597.appspot.com',
    androidClientId: '1094149306983-88lipmgrclqk7lu947q8sgtidi8bqsi1.apps.googleusercontent.com',
    iosClientId: '1094149306983-ot3urnibgdq4a4foqvndvj9qos6i4ei1.apps.googleusercontent.com',
    iosBundleId: 'com.example.monlivreur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArPzmblxhYgG6VtRjxUK7SXbTK0yGFcPs',
    appId: '1:1094149306983:ios:4e812677b3a2b93ec872c2',
    messagingSenderId: '1094149306983',
    projectId: 'pfee-76597',
    storageBucket: 'pfee-76597.appspot.com',
    androidClientId: '1094149306983-88lipmgrclqk7lu947q8sgtidi8bqsi1.apps.googleusercontent.com',
    iosClientId: '1094149306983-ot3urnibgdq4a4foqvndvj9qos6i4ei1.apps.googleusercontent.com',
    iosBundleId: 'com.example.monlivreur',
  );
}
